### ISSUE TITLE
make failed on KZ machine

### ISSUE THREAD

**Issue by anitera** [kappazeta/cm-vsm#4]
After
`cmake -DCMAKE_CXX_COMPILER=g++-8 ..`
`make`
it is throwing an error:
`
...`
`sar/data/cvat/code/cvat-vsm/vsm/lib/raster/jp2_image.cpp:274:8: error: ‘opj_end_decompress’ was not declared in this scope
   if (!opj_end_decompress(l_codec, l_stream)) {
        ^~~~~~~~~~~~~~~~~~
/sar/data/cvat/code/cvat-vsm/vsm/lib/raster/jp2_image.cpp:274:8: note: suggested alternative: ‘opj_create_decompress’
   if (!opj_end_decompress(l_codec, l_stream)) {
        ^~~~~~~~~~~~~~~~~~
        opj_create_decompress
/sar/data/cvat/code/cvat-vsm/vsm/lib/raster/jp2_image.cpp:288:3: error: ‘opj_stream_destroy’ was not declared in this scope
   opj_stream_destroy(l_stream);
   ^~~~~~~~~~~~~~~~~~
/sar/data/cvat/code/cvat-vsm/vsm/lib/raster/jp2_image.cpp:288:3: note: suggested alternative: ‘opj_image_destroy’
   opj_stream_destroy(l_stream);
   ^~~~~~~~~~~~~~~~~~
   opj_image_destroy
/sar/data/cvat/code/cvat-vsm/vsm/lib/raster/jp2_image.cpp:290:3: error: ‘opj_destroy_codec’ was not declared in this scope
   opj_destroy_codec(l_codec);
   ^~~~~~~~~~~~~~~~~
/sar/data/cvat/code/cvat-vsm/vsm/lib/raster/jp2_image.cpp:290:3: note: suggested alternative: ‘opj_destroy_compress’
   opj_destroy_codec(l_codec);
   ^~~~~~~~~~~~~~~~~
   opj_destroy_compress
lib/CMakeFiles/libvsm.dir/build.make:158: recipe for target 'lib/CMakeFiles/libvsm.dir/raster/jp2_image.cpp.o' failed
make[2]: *** [lib/CMakeFiles/libvsm.dir/raster/jp2_image.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'lib/CMakeFiles/libvsm.dir/all' failed
make[1]: *** [lib/CMakeFiles/libvsm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by indrek-sunter** [comment]
CMake `FIND_PATH` for OpenJPEG headers found `openjpeg.h` from `/usr/include/` before looking into `/usr/include/openjpeg-2.3`. Implemented a work-around with multiple `FIND_PATH` calls, based on [https://cmake.org/cmake/help/latest/command/find_path.html](https://cmake.org/cmake/help/latest/command/find_path.html).
